version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PORT: 8000
      DATABASE_URL: postgres://postgres:dev_password@db:5432/hiss
      MAILGUN_API_KEY: "YOUR_MAILGUN_API_KEY"
      SECRET_KEY: "SOME_SECRET_STRING"
      AWS_ACCESS_KEY_ID: "YOUR_AWS_KEY"
      AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET"
      AWS_S3_BUCKET_NAME: "YOUR_S3_BUCKET"
      AWS_S3_KEY_PREFIX: "YOUR_S3_PREFIX"
    expose:
      - 8000