name: Run Unit Tests

on: [push]

jobs:
  pylint:
    name: 'Check that tests are passing for supported Python versions'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6,3.7]
    steps:
      - uses: actions/checkout@v1
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r hiss/requirements.txt
      - name: Run tests
        run: |
          cd hiss
          python manage.py test
