name: Test Application

on: [push]

env:
  MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  django-tests:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ouroboros .
      - name: Run tests
        run: docker run ouroboros python3 manage.py test
